/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RitualsRouteImport } from './routes/rituals'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as IndexRouteImport } from './routes/index'

const RitualsRoute = RitualsRouteImport.update({
  id: '/rituals',
  path: '/rituals',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/carte': typeof CarteRoute
  '/reserve': typeof ReserveRoute
  '/rituals': typeof RitualsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/carte': typeof CarteRoute
  '/reserve': typeof ReserveRoute
  '/rituals': typeof RitualsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/carte': typeof CarteRoute
  '/reserve': typeof ReserveRoute
  '/rituals': typeof RitualsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atelier' | '/carte' | '/reserve' | '/rituals'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atelier' | '/carte' | '/reserve' | '/rituals'
  id: '__root__' | '/' | '/atelier' | '/carte' | '/reserve' | '/rituals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  CarteRoute: typeof CarteRoute
  ReserveRoute: typeof ReserveRoute
  RitualsRoute: typeof RitualsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rituals': {
      id: '/rituals'
      path: '/rituals'
      fullPath: '/rituals'
      preLoaderRoute: typeof RitualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  CarteRoute: CarteRoute,
  ReserveRoute: ReserveRoute,
  RitualsRoute: RitualsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
